In [1]:
import pandas as pd

df = pd.read_csv("clean_jobs_data.csv")
df.head()

,country,search_keyword,title,company,location,salary_min,salary_max,contract_type,created,description,...,skill_power_bi,skill_excel,skill_tableau,skill_spark,skill_airflow,skill_snowflake,skill_aws,skill_azure,skill_r,skill_sas
0,fr,data analyst,Data analyst (f/h) (CDI),MICHAEL PAGE,"Éguilles, Pélissanne",NaN,NaN,permanent,2026-06-30 07:28:19+00:00,l'entreprise opère dans un environnement multi...,...,False,False,False,False,False,False,False,False,False,False
1,fr,data analyst,Data Analyst,Microsoft Learn Student Club VIT Pune,"Paris, Ile-de-France",NaN,NaN,NaN,2026-06-20 12:25:52+00:00,we’re hiring: data analyst love turning dat...,...,False,False,False,False,False,False,False,False,False,False
2,fr,data analyst,Data Analyst / Data Scientist,Momentum One Zero,"Paris, Ile-de-France",NaN,NaN,NaN,2026-06-27 12:05:58+00:00,data analyst / data scientist location: franc...,...,False,False,False,False,False,False,False,False,False,False
3,fr,data analyst,Data Analyst (H/F) (Intérim),Robert Walters,"1er Arrondissement, Paris",NaN,NaN,contract,2026-06-29 23:34:21+00:00,"acteur majeur de l'assurance en europe, cette ...",...,False,False,False,False,False,False,False,False,False,False
4,fr,data analyst,Data Analyst (H/F) (CDI),Nacimut,"Poissy, Saint-Germain-en-Laye",NaN,NaN,permanent,2026-06-23 18:40:25+00:00,"notre client est une maison française, reconnu...",...,True,False,False,False,False,False,False,False,False,False

In [2]:
#create new column = averae of salary_min & salary_max

df["salary_avg"] = (df["salary_min"] + df["salary_max"]) / 2
df[["title", "country", "salary_min", "salary_max", "salary_avg"]].head()

                           title country  salary_min  salary_max  salary_avg
0       Data analyst (f/h) (CDI)      fr         NaN         NaN         NaN
1                   Data Analyst      fr         NaN         NaN         NaN
2  Data Analyst / Data Scientist      fr         NaN         NaN         NaN
3   Data Analyst (H/F) (Intérim)      fr         NaN         NaN         NaN
4       Data Analyst (H/F) (CDI)      fr         NaN         NaN         NaN

In [ ]:
df["salary_missing"] = df["salary_avg"].isna() 
# Group by country, count how many True (missing) values per group
df.groupby("country")["salary_missing"].sum()

country
de    421
fr    351
gb      1
nl    287
Name: salary_missing, dtype: int64

In [5]:
# Loop through each country, print its top 5 highest paid offers
for country in df["country"].unique():
    print(f"\n--- Top 5 highest paid offers in {country} ---")
    top5 = df[df["country"] == country].sort_values("salary_avg", ascending=False).head(5)
    print(top5[["title", "company", "salary_avg"]])

--- Top 5 highest paid offers in fr ---
                                                 title  \
145                                   Data analyst H/F
409  Responsable Contrôle de Gestion Industriel Gro...
398       Expert SAP Bw - Consultant SAP Bi Senior H/F
428  Directeur Marketing Opérationnel & Market Inte...
432  Directeur Marketing Opérationnel & Market Inte...

                         company  salary_avg
145                          NaN    109200.0
409  LM5P - Le Mouton à 5 Pattes     80000.0
398                  The Porters     78350.0
428                     Adito RH     72500.0
432                     Adito RH     72500.0

--- Top 5 highest paid offers in de ---
                                       title           company  salary_avg
735  Business Analyst Schwerpunkt Wertpapier    SThree Germany    228800.0
558       SAP Ariba Catalog and Data Analyst  N Consulting Ltd    178100.0
559       SAP Ariba Catalog and Data Analyst  N Consulting Ltd    136500.0
493                  Data Analyst, Marketing            Quince    117500.0
515                     Data Analyst (m/w/d)    SThree Germany    110000.0

--- Top 5 highest paid offers in gb ---
                                title                                 company  \
1343                Staff AI Engineer  Harnham - Data & Analytics Recruitment
1034                     Data Analyst                       Huxley Associates
1045                     Data Analyst        Sanderson Government and Defence
1150  Senior Systems Business Analyst                     Cathcart Technology
1186                 Business Analyst                Mentmore Recruitment Ltd

      salary_avg
1343    175000.0
1034    156000.0
1045    147030.0
1150    143000.0
1186    143000.0

--- Top 5 highest paid offers in nl ---
                                                title  \
1546                              IT Business Analyst
1683                                    BI Consultant
1395                          Business & Data Analyst
1425  Business Data Analyst Governance & Architecture
1617            IT Business Analyst & Project Manager

                        company  salary_avg
1546    Oliver James Associates    176800.0
1683                 Freshminds    110000.0
1395  LexisNexis Risk Solutions     95650.0
1425                        APG     89658.0
1617                ROBERT HALF     84000.0